### ISSUE TITLE
packing and building with ffmpeg-static-electron

### ISSUE THREAD

**Issue by yafp** [yafp/media-dupes#22]
The builds for each single platform do currently contain the ffmpeg binaries for all supported platforms

This is due to the usage of: https://github.com/pietrop/ffmpeg-static-electron

**Example:**

The windows x64 build contains ffmpeg binaries for
* win32
* win64
* mac
* linux32
* linux 64

this heavily raises the build size.

The question is - how to improve that?

Maybe using some package.json scripts which is used to post-process the packaging and removes the un-needed files.

**Comment by yafp** [comment]
Other idea:
check if electron-builder offers an IGNORE option

**Comment by yafp** [comment]
https://github.com/electron-userland/electron-builder/issues/383#issuecomment-365863333

**Comment by yafp** [comment]
Seems like i got a working solution

adding a files section to the win build specification helped


```
"win": {
      "icon": "resources/installer/icon.ico",
      "publisherName": "yafp",
      "artifactName": "${productName}-${version}-win-${arch}.${ext}",
      "files": [
        "!node_modules/ffmpeg-static-electron/bin/linux/*",
        "!node_modules/ffmpeg-static-electron/bin/mac/*"
      ],
      "target": [
        "zip",
        "nsis",
        "portable"
      ]
    },
```

so i've added:
```
"files": [
        "!node_modules/ffmpeg-static-electron/bin/linux/*",
        "!node_modules/ffmpeg-static-electron/bin/mac/*"
      ],
```
This reduced the build size about 40-50 MB.

Using this approach i still have the binaries for:

* 64 bit
* 32 bit

in my 64bit windows build .... but not the linzx&mac os versions anymore.

Should test a bit more with the structure of my package.json and the files section ...but it seems like the way to go.

**Comment by derhuerst** [comment]
Let's solve this upstream! See also https://github.com/eugeneware/ffmpeg-static/issues/35 .
